UI 구현
ESTsoft-Back-end-6th-2nd-project-team3/ESTsoft-2nd-Project pull request #12
Opened 2024-11-06 06:33 UTC by zeonzyeon

- 마이페이지 내 정보 UI
- 내 정보 수정 UI
- 게시글 목록 UI

- 관리자 권한에 따라 버튼 활성화
- 게시글 필터링

2024-11-06 07:40 UTC, Jindo-Dog requested changes

2024-11-06 07:40 UTC, Jindo-Dog commented on .gitignore
> -build
ignore에 build가 빠졌어요

2024-11-06 07:40 UTC, Jindo-Dog commented on build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
중복이에요

2024-11-06 08:04 UTC, Jindo-Dog approved these changes, later dismissed

2024-11-06 08:05 UTC, tmfrl99 submitted a review, later dismissed

2024-11-06 08:53 UTC, anhyeongmin approved these changes, later dismissed

2024-11-07 01:49 UTC, Jindo-Dog approved these changes

2024-11-07 01:56 UTC, anhyeongmin approved these changes

2024-11-07 02:03 UTC, merged