Feature/main and admin
ESTsoft-Back-end-6th-2nd-project-team3/ESTsoft-2nd-Project pull request #29
Opened 2024-11-11 04:12 UTC by anhyeongmin

fragment/main-page-signin.html - 로그인창

controller/main/LoginController.java - 로그인 컨트롤러

2024-11-11 04:32 UTC, Jindo-Dog requested changes

2024-11-11 04:32 UTC, Jindo-Dog commented on src/main/java/com/estsoft/estsoft2ndproject/domain/Objective.java
> +	private String objectiveYearMonth;
DATE 타입으로 받아온 것은 변환해서 써주세요

2024-11-11 04:32 UTC, Jindo-Dog commented on src/main/java/com/estsoft/estsoft2ndproject/domain/User.java
> +	@OneToMany(mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
User 엔티티에 Post 리스트를 넣은 이유가 있나요?

2024-11-11 04:32 UTC, Jindo-Dog commented on src/main/java/com/estsoft/estsoft2ndproject/domain/dto/mypage/ObjectiveRequestDTO.java
> +	private String objectiveYearMonth;
이 부분에서 생성자를 통해 변환하셔도 됩니다

2024-11-11 04:32 UTC, Jindo-Dog commented on src/main/resources/static/css/board.css
> +/* 게시글 컨테이너 */
클래스들을 모두 빼놓으면 다른 스타일에서 영향을 받습니다. 적용 영역을 축소해주세요.
당장 h2만 해도 이렇게 적혀있으면 모든 h2가 이 스타일의 영향을 받아요

2024-11-11 04:32 UTC, Jindo-Dog commented on src/main/resources/static/css/login.css
> +/* 로그인 컨테이너 */
base.css에 통합해주세요

2024-11-11 04:32 UTC, Jindo-Dog commented on src/main/resources/static/css/object.css
> +/* 초기화 */
역시 base.css에 통합해주세요

2024-11-11 04:32 UTC, Jindo-Dog commented on src/main/resources/templates/fragment/board-list.html
> +                <span class="category" th:text="${post.postType}">카테고리</span>
나중에 카테고리나 제목 눌러서 해당 항목으로 이동할 수 있어야 하니 인지하고 계셔주세요

2024-11-11 04:32 UTC, Jindo-Dog commented on src/main/resources/templates/main-page-post.html
> +<!-- 첫 번째 게시글 목록 (제목: 게시글) -->
이렇게 분리한 이유가 있나요? 아니면 테스트용 페이지인가요?

2024-11-11 07:48 UTC, Jindo-Dog requested changes

2024-11-11 07:48 UTC, Jindo-Dog commented on src/main/java/com/estsoft/estsoft2ndproject/controller/api/MyPageController.java
>  	@GetMapping("/userinfo")
저희 다른 사람이 마이페이지를 볼 수 있어야 해서 userId는 필요해요

2024-11-11 07:48 UTC, Jindo-Dog commented on src/main/java/com/estsoft/estsoft2ndproject/controller/api/PostApiController.java
> +	private final ActivityScoreRepository activityScoreRepository;
사용하지 않는 구문 같아요

2024-11-11 07:48 UTC, Jindo-Dog commented on src/main/java/com/estsoft/estsoft2ndproject/domain/User.java
> +		this.activityScore = activityScore;
저희 등급에 대한 명칭은 통일해 주세요

2024-11-13 03:37 UTC, Jindo-Dog approved these changes

2024-11-13 03:48 UTC, tmfrl99 approved these changes

2024-11-13 03:52 UTC, zeonzyeon approved these changes

2024-11-13 04:02 UTC, merged